Fix installer bug

diff --git a/install b/install
--- a/install
+++ b/install
@@ -22,10 +22,9 @@ for file in ~/.bashrc.d/config/*; do
 
   # Error out if it exists as an actual file
   if [ -f ~/.${file##*/} ]; then
-    continue
+    echo "ERROR: You need to backup and delete ~/.${file##*/} before install will proceed."
+    exit 1
   fi
-  echo "ERROR: You need to backup and delete ~/.${file##*/} before install will proceed."
-  exit 1
 done
 
 echo "Linking files..."
